# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Harold Chen
email: 
description:  # this means to ignore newlines until "baseurl:"
  
url: # the base hostname & protocol for your site

baseurl: 
permalink: /:title/

analytics: 
disqus-shortname:

#color scheme
# Tiffany Blue 81D8D0
# HKUST Blue
color-1: '#1993f0' # deep blue
# color-1: '#19a9f0' # shallow blue
# Stanford Red
# color-1: '#E64C3C' 
color-2: '#19a9f0'

# Author pictre 100x100 --> keep it inside img folder.
author-image: 
author-name: 'Harold Chen'
author-about: '' 

# Build settings
markdown: kramdown

sass:
    style: compressed

repo_theme_light: default # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_theme_dark: vision-friendly-dark # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_trophies:
  enabled: true
  theme_light: flat # https://github.com/ryo-ma/github-profile-trophy
  theme_dark: gitdimmed # https://github.com/ryo-ma/github-profile-trophy


#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
  
  
prose:
  rooturl: ''
  siteurl: 'http://prose.github.io/starter/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    
gems: [jekyll-seo-tag]
